id: IA7F68197
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:01:58+00:00'
last_modified: '2022-06-10T06:37:29.601449+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19380
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    014C:
      image_group_id: I2PD20435
      title: Volume 1 of dge rgan gyi slob gso/
      total_pages: 140
      order: 1
      base_file: 014C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
